apiVersion: v1
kind: Secret
metadata:
  name: shop-tls-secret
  namespace: mentee-shop
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC7zCCAdegAwIBAgIUQn+a7hGK+P5zRiNvcDnuI3T9GUMwDQYJKoZIhvcNAQEL
    BQAwHzEdMBsGA1UEAwwUc2hvcC5tZW50ZWUtcG93ZXIucnUwHhcNMjYwNjE5MDgz
    MTE2WhcNMjcwNjE5MDgzMTE2WjAfMR0wGwYDVQQDDBRzaG9wLm1lbnRlZS1wb3dl
    ci5ydTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALvpz1TnXz/hDu1b
    EvZhxVJdgIzAxSTLhgXplnyvMHVrWirhzaYWMH3xxMvbLnOogjyRn6tAUbArcPIe
    4RwnoH0jD/uL3eUwIEvFlrpx5kG11LExboq8AnG2NuZqfgQmF4ekYs8guUf0yg42
    m3FecM4ist/z65JNhqFiTP8b387/neckv+a4qsgKb/zlBagPUp5iUqNMJY0byqCa
    sGQYCg8wMv7bdWBtHXzPP7GS4yNb0a0BxXz/Z7XqKGKXjqhd7P5AKACx+7A4vKZe
    rEhsm8dVM7/vTgf7yrWJFT0Yj9ty7OmnV3QmK4JM+L3Q5y2/meaf+dbkRh7cD4QM
    a7Q7X3MCAwEAAaMjMCEwHwYDVR0RBBgwFoIUc2hvcC5tZW50ZWUtcG93ZXIucnUw
    DQYJKoZIhvcNAQELBQADggEBAArtelnlJX7ky+MuzxUaOgCpnFKSqwEXAdnymNY4
    NdiW6UiN6yxFVPdJgALxik4IkCg5CGWotwc/+Bc4G5ZIaf0pl7wihY/7zvWdFNYz
    G7yzv8d2RAs17haI8gecjio+URm11aTCQhIke4Oa1qZQEWeXKlEBlsSXf0gk9A5c
    +Mi8tyYOsZ6LT2DRxeSWZmE/dYhxLELHfY3cwV7EkzHoehPMlvtZe09VpvZfMFQu
    EzS1ZK1l6B3tMlU3MU3yputE7R4KaZ4vrK9HyZD9dGPIYwioAgSY5gqhiGzjVc4d
    WGLy2rpXEGCJxg8lkEZ3borDTJtyVp0Li8SZyo6VchK+hlQ=
    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC76c9U518/4Q7t
    WxL2YcVSXYCMwMUky4YF6ZZ8rzB1a1oq4c2mFjB98cTL2y5zqII8kZ+rQFGwK3Dy
    HuEcJ6B9Iw/7i93lMCBLxZa6ceZBtdSxMW6KvAJxtjbman4EJheHpGLPILlH9MoO
    NptxXnDOIrLf8+uSTYahYkz/G9/O/53nJL/muKrICm/85QWoD1KeYlKjTCWNG8qg
    mrBkGAoPMDL+23VgbR18zz+xkuMjW9GtAcV8/2e16ihil46oXez+QCgAsfuwOLym
    XqxIbJvHVTO/704H+8q1iRU9GI/bcuzpp1d0JiuCTPi90Octv5nmn/nW5EYe3A+E
    DGu0O19zAgMBAAECggEABirOgSzZdW2xRNXclTybVfB3qENhmI7iwvEi+a+456Uy
    imHAIWzeyTi4ir52IdKBwCx6AppiBbtAJXzLvFXt8HusG7kjpaYxJZm0FAkU7/Vg
    bzL+H1OC+s1OJbzl46gUY2TR/AgQBYqMRHAKXfntD6GJrq+BJ4YRnqOluCjLJhH6
    UDsgVpn2+wvuSjCjKCmUc3eoIVpnR0JpidN1mm6VQ4QQj5WNKjVe1UGRV1vugTUW
    r/Mdn6H2yDozHJOGsHxLtO8pjH1U7eOoDYJPUp1KM6lrdtXvShdcAsDD/rplFhpi
    h/nMrueaobVMygjrsKua7DfqUm8p7dXgTQzLGXKroQKBgQDbb4r0eumDzi81c72P
    WgVlXZfpQjFfabhh0XPFIiv5PX7X1q5A6GXRYiBmh1Sm/Lx1SiwFw8ZUtCZACyUf
    cIMqVHrNepzUonNWi347j1hX/T7EhcdCRmYuuFrARW/CifqSXhfSAfp9ixVP3d+L
    Qm2yvJZor++afeTzjipqIqZYSwKBgQDbOZ45Izk1qsVoaREjNnAbCz66uNoOs5lF
    O70ci4Hvgg4u1/8Kp7SL7jNyCSme9gf6sSyGqcyjBoPY720t3Hz5y5M6Zze2E7SO
    xu/yPVSmfVnndd7Yu6KwgALd0mz4UWacOmAtrwWl7X4IwJUVsV/qn6K/jha4T6hh
    dswdcZRseQKBgDIyggcLVv/f2szPfT2dyj41+tpRWhoJhTRbRbCC8KxDdRDK+3G9
    uAz99Yt+yc6pYjMylH99GZGm5FkiM4vNoTO9v5nhwp6hyuCxaF8Xm44FUKaEM+Dl
    Wdq2MYxqVfaaucdh3vEbosG1X1q11r10pMOOgJnSJW2h/w34J5u/8W2hAoGALmY4
    jeFdp3U4iQvL28cW3TJ5GW4sgPYUV6n4McV5P+cn91QyH+A0/3TwII+95m4ubCn5
    wZrIvCyR1WV/lzhWn0wuIitciEYNbja+7Gd8tixLzgiNnRPBsFe3w5lZBQm9jQ1x
    89laea8VgOa55zh+k5ssCB0bw/DgM5jARO8YOgkCgYEAthqwgQYakfzyQizlsoTp
    fA9YTp9n0Z5A1DQ+pi8o9RzT2/FxGTR4ysR+77m/QMsfTA8NmyZMqxpkmZMAPYDF
    OYD3kQ2b2f+3UZn2oM9u20rHVGt4Vh5L3UBJQAbiDmE7+bbUPuw49WrWB0fljoBU
    IiPk0REWYa2hH4lDrRgu8FI=
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-tls-secret
  namespace: mentee-shop
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC8jCCAdqgAwIBAgIUdCgZNgWDGrbGhIpV41SxoDwurWswDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVYWRtaW4ubWVudGVlLXBvd2VyLnJ1MB4XDTI2MDYxOTA4
    MzEyOVoXDTI3MDYxOTA4MzEyOVowIDEeMBwGA1UEAwwVYWRtaW4ubWVudGVlLXBv
    d2VyLnJ1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAudIg0czyAfiC
    EcNGn34e+rlN23Pzh3QF9R2o/49EjSNP1KpZ4wmTBqqzZEZOcDHHWdidsL2EXC0o
    94nP1sk6+lXbfgpdDukbzChBjYM0WhZan5z9wRC/JCCjVHDQHNb+h30HumhxkzqF
    Uj+Rr7VsRjoVkGZRCKHyNeV8r1CyG8DoBr9E6O7Q6ugi7pBcWhwMiMrmyiRy+yIq
    X6/EE8x7idPep9zBmbAOGg+2V6rw0DNh/SU4Fjq9c32zssnJ7BSRBi10T/Lq4sM+
    5ciqFH/bMaCQOmkcHwKGvvPz/Nx+Jcsmmm5SF02jX8wZ7lbub1jhl4oVDcJ1IRcC
    +tbSR88ltwIDAQABoyQwIjAgBgNVHREEGTAXghVhZG1pbi5tZW50ZWUtcG93ZXIu
    cnUwDQYJKoZIhvcNAQELBQADggEBAHkgf5zX5bpH59dECkM+I82/JECBbQBKh9lQ
    b+OL1epIU9wzqLHfXdoOQTj1gadRKqg6rtg4tBzTyL6w9GhUgcbJOmx9n6eC1t/N
    6L9vxjSHEDtB5WEeK7Ok7ZfitjNV6NXgiGhbzX4uZjunDV7hDYZTw7+j+0jMCtQr
    rYVjsiVAo8ZcoqOQnmPw+W5/PayFBh7yAdr74tGjUsUvVIw0vg90PvuVnR+pqmGH
    wNSC84ghKT4sCxP46Z3qU7vFoJVc+gLFOef0Jp74aQm4ifH1AANfFsR1mVWU6uVW
    dFPv1TG+Mbm/8ZOwcP0Jxo6Tt1SEE327VsjhM/9kNbdfCuQdVkM=
    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC50iDRzPIB+IIR
    w0affh76uU3bc/OHdAX1Haj/j0SNI0/UqlnjCZMGqrNkRk5wMcdZ2J2wvYRcLSj3
    ic/WyTr6Vdt+Cl0O6RvMKEGNgzRaFlqfnP3BEL8kIKNUcNAc1v6HfQe6aHGTOoVS
    P5GvtWxGOhWQZlEIofI15XyvULIbwOgGv0To7tDq6CLukFxaHAyIyubKJHL7Iipf
    r8QTzHuJ096n3MGZsA4aD7ZXqvDQM2H9JTgWOr1zfbOyycnsFJEGLXRP8uriwz7l
    yKoUf9sxoJA6aRwfAoa+8/P83H4lyyaablIXTaNfzBnuVu5vWOGXihUNwnUhFwL6
    1tJHzyW3AgMBAAECggEAAnbz4RLaJ4QFJgy3p9POD0iPM0YMJpKYwFJlB0Ghrkre
    hi6bfl2lOvvxBEJrFuwLNQQPFOcQipf29L5l8Y1JApR/MZMKaJArWJSNAeYBE8+B
    68KR2DxJMojn8a/u0nJG9G+MyCgoLPC6X3PjMR/L2mww+isUSUfwnSJKUq+E0fH7
    VyGa/6GFf0o7fm9Fzm0MmTJ98XO+nYWv3FeuDwBmUUsGkebxvRSZk3Vu92AtKpVI
    WA++wSF7+TKbBKHusMXveDXPYxAW+7623L8MXmTUHLwFHkndl0NctD4GSBIjMCQK
    Ct8IwcLwJxcFpyApiFT7Zp5JWMTZM4WQI4NUVxYsbQKBgQDfopHX1sLqqMuCSETv
    1eKpEbzUDct+UyjOSoUoTJUNpuvNjjsWvxNhsO2g23L5pUOG/Yt9smHS1ffYoD4f
    zhjkxwqSQqjVIcmmuJe/E/PG1aOi6Zwzc20ErAC9JLhYB3sUTXyaQPzVdwzbRX0+
    VnoTm4Cn08zjt1ylhNfUOXeLQwKBgQDUtpVZAWywJoSr3iGYJBsrWGj84fvNMLKC
    mSCzXxIoHQk0Clf1mZBmgS2Yw2FoNhJwxOMB0szGi8NsvGxAGzWK3SbUiDDPXs+6
    Ytj6024UNr1xoS81BUJQuqdH9VdcrVWG2p5cdsxhCTpkhU96dq+R2xqVjVFDk0WM
    C9ofARXifQKBgHvCT8uOgheyiczziZLgXqsJseH4MGEcTDy9aKtAlkwTz/LVf0W7
    QFKTwy19xEb7ej8+GO/aw+AVoS80nqyjNYuFywfd8+je5eVpyjBoLkQe/outlE+0
    1OP8+/uwUoQEv8wghZAn3sOTOn4uGn1hBfXL3IsD3yM12gOPXJGJq+pZAoGBALSc
    /7zef8omOpqwdzf22Hb6j9LBk4vL4JcRrHmBrSoQVYMxkTRCGyFeaDgBFhFlcEz+
    cH5Y3nVrsRj/+K6KK/FoDJODvGYn7Bwn2HNJ2Xsia8MzCKFtgLyJcIaiJHbV2vwx
    XyvF145BRqqZoz2pzzP6pdz8bFcDkpbybVfMFSgFAoGAIub4oh3HOrUtFvP10lif
    m6/flWqLRqL6hcCku+e3YNzbUQfhaR4EnAQkvhgD/iajT7ty7udvraMK4e5xTP7y
    QOkjpnI8VRWNYmLxsaUgTbrSOzOMO7TUu0XG6bEdqidI1e1aq89msgKukLv6iC2q
    VQiUWALglsslXUnv+2V8IG0=
    -----END PRIVATE KEY-----
