apiVersion: v1
kind: Service
metadata:
  name: config-vault-app-service
spec:
  type: NodePort
  selector:
    app: config-vault-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080