apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  namespace: configurable-calculator-app
spec:
  selector:
    app: calculator-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer