apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: configurable-calculator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-app
  template:
    metadata:
      labels:
        app: database-app
    spec:
      containers:
        - name: database-container
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: calculator-config
                  key: DATABASE_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: calculator-secret
                  key: database-user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calculator-secret
                  key: database-password