apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: configurable-calculator-app
spec:
  selector:
    app: database-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP