apiVersion: v1
kind: Secret
metadata:
  name: calculator-secret
  namespace: configurable-calculator-app
type: Opaque
data:
  database-password: cXdlcnR5MTIz
  database-user: Y2FsYy11c2Vy
  api-key: ODg0Ni0xNWEwLXhzOEQ=